export const SET_SELECTED_DEVICE = "SET_SELECTED_DEVICE";
export const SET_ALL_DEVICE = "SET_ALL_DEVICE";
export const SET_FILTERED_DEVICE = "SET_FILTERED_DEVICE";
export const SET_ALL_ANIMALS = "SET_ALL_ANIMALS";